@startuml

skinparam nodesep 10
skinparam ranksep 20

skinparam node {
  borderColor Green
  backgroundColor<<isolate>> darkkhaki
}

node #honeydew {

node process #cornsilk { 

node "v8" <<isolate>>
node "v8" <<isolate>> as n2
node "v8" <<isolate>> as n3
node "v8" <<isolate>> as n4
}


node process as p2 #cornsilk { 

node "v8" <<isolate>> as n5
node "v8" <<isolate>> as n6
node "v8" <<isolate>> as n7
label "Same origin tabs" as l1
}

}


n5 <- l1
n6 <-- l1
n7 <-- l1

@enduml