@startuml

<style>
componentDiagram {
  LineColor Green
}
</style>
node Browser as b #darkkhaki



node "WinUI3 App" #honeydew {
node LoginPage.xaml.cs as lp #cornsilk

node Program.cs as p #cornsilk
node App.xaml.cs as a #cornsilk
}


lp -> b : <color:Black>LaunchUri for authorizationRequest<color:Black>
b -[dashed]> p : <color:white> Invoked by declared \n<color:white>URL protocol<color:white>
p -[dashed]> a : <color:Black> RedirectActivationToAsync to main AppInstance<color:Black>
a --[dashed]> lp : <color:Black> Enqueue Navigate request \n<color:Black>in DispatcherQueue<color:Black>


@enduml